default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Play Store Internal Testing Track"
  lane :beta do
    sh("flutter", "build", "appbundle", "--no-shrink")
    
    upload_to_play_store(
      track: "internal",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_changelogs: true,
      changes_not_sent_for_review: true,
      aab: "../build/app/outputs/bundle/release/app-release.aab"
    )
  end

  lane :deploy do |options|
    upload_to_play_store(
      track: "internal",
      track_promote_to: "production",
      version_code: options[:version_code],
      skip_upload_apk: true,
      skip_upload_aab: true,
      skip_upload_metadata: true,
      skip_upload_changelogs: false,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end